<?xml version="1.0" encoding="UTF-8"?>

<FLOW VERSION="3.0" CLEANUP="true">
  <COMMENT>exit on success</COMMENT>

  <!-- nodes -->

<SEQUENCE TIMEOUT="" EXIT-ON="SUCCESS">
  <COMMENT>exit on success</COMMENT>

  <!-- nodes -->

<SEQUENCE TIMEOUT="" EXIT-ON="FAILURE">
  <COMMENT>exit on FAILURE [try]</COMMENT>

  <!-- nodes -->

<INVOKE TIMEOUT="" SERVICE="advTrainingISDemo.demo.errorHandling:myIntDivide" VALIDATE-IN="$none" VALIDATE-OUT="$none">
  <COMMENT></COMMENT>

  <!-- nodes -->

<MAP MODE="INPUT">
</MAP>

<MAP MODE="OUTPUT">
</MAP>
</INVOKE>

<EXIT FROM="$parent" SIGNAL="FAILURE" FAILURE-MESSAGE="Ouch!">
  <COMMENT></COMMENT>
</EXIT>
</SEQUENCE>

<SEQUENCE TIMEOUT="" EXIT-ON="DONE">
  <COMMENT>exit on DONE [catch]</COMMENT>

  <!-- nodes -->

<INVOKE TIMEOUT="" SERVICE="pub.flow:getLastError" VALIDATE-IN="$none" VALIDATE-OUT="$none">
  <COMMENT></COMMENT>

  <!-- nodes -->

<MAP MODE="INPUT">
</MAP>

<MAP MODE="OUTPUT">
</MAP>
</INVOKE>

<BRANCH TIMEOUT="" SWITCH="/lastError/errorType">
  <COMMENT></COMMENT>

  <!-- nodes -->

<EXIT NAME="java.lang.ArithmeticException" FROM="$flow" SIGNAL="FAILURE" FAILURE-MESSAGE="Custom Exception due to java.lang.ArithmeticException">
  <COMMENT></COMMENT>
</EXIT>
</BRANCH>
</SEQUENCE>
</SEQUENCE>
</FLOW>
